import { Track } from '@/types/database.types'

export const mockTracks: Track[] = [
  {
    id: 'track-1',
    title: 'Uplifting Corporate',
    artist: 'Brandmusic Studio',
    duration: 180,
    bpm: 128,
    key: 'C Major',
    genre: ['Corporate', 'Pop'],
    mood: ['Uplifting', 'Energetic', 'Confident'],
    energy: 0.8,
    cover_url: 'https://images.unsplash.com/photo-1611339555312-e607c8352fd7?w=400&h=400&fit=crop',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  },
  {
    id: 'track-2',
    title: 'Calm Piano Journey',
    artist: 'Brandmusic Studio',
    duration: 210,
    bpm: 90,
    key: 'A Minor',
    genre: ['Ambient', 'Piano'],
    mood: ['Calm', 'Reflective', 'Peaceful'],
    energy: 0.3,
    cover_url: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=400&h=400&fit=crop',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  },
  {
    id: 'track-3',
    title: 'Tech Startup Energy',
    artist: 'Brandmusic Studio',
    duration: 195,
    bpm: 140,
    key: 'D Major',
    genre: ['Electronic', 'Tech'],
    mood: ['Energetic', 'Modern', 'Innovative'],
    energy: 0.9,
    cover_url: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=400&h=400&fit=crop',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  },
  {
    id: 'track-4',
    title: 'Acoustic Brand Story',
    artist: 'Brandmusic Studio',
    duration: 165,
    bpm: 85,
    key: 'G Major',
    genre: ['Acoustic', 'Folk'],
    mood: ['Warm', 'Authentic', 'Hopeful'],
    energy: 0.5,
    cover_url: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400&h=400&fit=crop',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  },
  {
    id: 'track-5',
    title: 'Cinematic Drama',
    artist: 'Brandmusic Studio',
    duration: 240,
    bpm: 100,
    key: 'E Minor',
    genre: ['Cinematic', 'Orchestral'],
    mood: ['Dramatic', 'Epic', 'Powerful'],
    energy: 0.7,
    cover_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
  },
  {
    id: 'track-6',
    title: 'Funky Product Launch',
    artist: 'Brandmusic Studio',
    duration: 175,
    bpm: 115,
    key: 'F Major',
    genre: ['Funk', 'Pop'],
    mood: ['Playful', 'Confident', 'Fun'],
    energy: 0.85,
    cover_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
  },
]
